name: deploy

on: deployment

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install app
      run: npm i
    - name: Run enzyme/jest unit tests
      run: npm run test
    - name: Build static files
      env:
        SPACE_ID: ${{ secrets.SPACE_ID }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: npm run build SPACE_ID=$SPACE_ID ACCESS_TOKEN=$ACCESS_TOKEN
#     - name: Deploy to github pages
#       run: npm run deploy
