name: deploy

on: deployment

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install app
      run: npm i
    - name: Run enzyme/jest unit tests
      run: npm run test
    - name: Build static files
      run: npm run build
#     - name: Deploy to github pages
#       run: npm run deploy
