name: deploy

on: deployment

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install app
      run: npm i
    - name: Run enzyme/jest unit tests
      run: npm run test
    - name: Build static files
      env:
        SPACE_ID: ${{ secrets.SPACE_ID }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: npm run build SPACE_ID=$SPACE_ID ACCESS_TOKEN=$ACCESS_TOKEN
    - name: Copy static folder (CNAME)
      run: npm run gatherStaticDist
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAT }}
        PUBLISH_BRANCH: master
        EXTERNAL_REPOSITORY: electricdreammachine/electricdreammachine.github.io
        PUBLISH_DIR: ./public
