name: deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run enzyme/jest unit tests
      run: npm run test
    - name: Deploy to github pages
      run: npm run deploy
